# Workflow 이름
name: Github Actions Execution

# Event : 실행되는 시점을 설정
# main 브랜치에 push 될 때 아래 Workflow가 실행되도록 설정
on:
  push:
    branches: 
        - main

# 하나의 Workflow는 1개 이상의 Job으로 구성될 수 있음
# 여러 Job은 병렬로 수행
jobs:
    # Job을 식별하기 위한 id
    My-Deploy-Job:
        # Job이 실행될 환경을 설정
        # ubuntu-latest : 최신 버전의 우분투 환경에서 실행
        runs-on: ubuntu-latest

        # Steps : 특정 작업을 수행하는 가장 작은 단위
        # Job은 여러 Steps로 구성
        steps:
            - name: Hello World Action
              run: echo "Hello, World!"

            - name : 여러 명령어 문장 작성하기
              run: |
                echo "Good"
                echo "Morning"

            - name : Github Actions에서 제공하는 환경 변수 사용하기
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
            
